import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/provider/providers";
// import Footer from "@/components/Layout/Footer";
import ClearHistoryOnUnload from "@/components/history/ClearHistoryOnUnload";
// import Header from "@/components/Layout/header/Header";
import Layout from "@/commons/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center w-full gap-5">
        <ClearHistoryOnUnload />
        <Providers>
          {/* 각 페이지별 적용되는 헤더를 위해 Layout으로 관리 */}
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
